[package]
name = "RusticJourney"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lifetimes"
, "rust-leetcode-exercises", "interview-questions", "macros", "rust-crypto", "machine-coding-questions", "tiny-rust-projects/redis", "async-rust", "tiny-rust-projects/write-json"]
