[package]
name = "interview-questions"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
crossbeam = "0.8.4"
parking_lot = "0.12.3"
rand = "0.9.1"
